services:
  server:
    build: .
    volumes:
      - server-logs:/usr/app/logs
    ports:
      - "${APP_PORT:-8080}:${APP_PORT:-8080}"
    environment:
      NODE_ENV: ${NODE_ENV:-dev}
      APP_PORT: ${APP_PORT:-8080}
      LOG_TO_CONSOLE: ${LOG_TO_CONSOLE:-true}

      COSMOS_RPC_NODE: ${COSMOS_RPC_NODE:-https://sei-m.rpc.n0ok.net:443}

    healthcheck:
      test: curl --fail http://localhost:8080/healthz
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  server-logs: