services:
  server:
    build: .
    volumes:
      - server-logs:/usr/app/logs
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      NODE_ENV: ${NODE_ENV:-dev}
      PORT: "${PORT:-8080}"
      LOG_TO_CONSOLE: ${LOG_TO_CONSOLE:-true}

    healthcheck:
      test: curl --fail http://localhost:8080/healthz
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  server-logs: